
import java.awt.Color;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KIDDY
 */
public class AddClass extends javax.swing.JFrame {

    /**
     * Creates new form AddClass
     */
    public AddClass() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
        AutoGenerateID auto = new AutoGenerateID();
        tf_idClass.setText(auto.autoIDClass());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_idClass = new javax.swing.JTextField();
        tf_className = new javax.swing.JTextField();
        tf_price = new javax.swing.JTextField();
        cb_bedType = new javax.swing.JComboBox();
        cb_roomSize = new javax.swing.JComboBox();
        cb_bathroom = new javax.swing.JComboBox();
        cb_facility = new javax.swing.JComboBox();
        btn_submit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 450));
        setMinimumSize(new java.awt.Dimension(400, 450));
        setPreferredSize(new java.awt.Dimension(400, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 450));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Class");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 30, 197, 55);

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Class");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 100, 60, 15);

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Class Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 140, 80, 15);

        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 180, 50, 15);

        jLabel5.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bed Type");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 220, 70, 15);

        jLabel6.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Room Size");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 260, 80, 15);

        jLabel7.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bathroom");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 290, 70, 15);

        jLabel8.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Facility");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 330, 35, 13);

        tf_idClass.setEditable(false);
        getContentPane().add(tf_idClass);
        tf_idClass.setBounds(140, 100, 177, 20);
        getContentPane().add(tf_className);
        tf_className.setBounds(140, 140, 177, 20);

        tf_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_priceKeyTyped(evt);
            }
        });
        getContentPane().add(tf_price);
        tf_price.setBounds(140, 180, 177, 20);

        cb_bedType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double Single", "King Size", "Queen Size" }));
        cb_bedType.setSelectedIndex(-1);
        getContentPane().add(cb_bedType);
        cb_bedType.setBounds(140, 210, 177, 20);

        cb_roomSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5 x 5", "8 x 5", "8 x 8", "10 x 10" }));
        cb_roomSize.setSelectedIndex(-1);
        getContentPane().add(cb_roomSize);
        cb_roomSize.setBounds(140, 250, 177, 20);

        cb_bathroom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Shower", "Bathroom", "Jaccuzzi" }));
        cb_bathroom.setSelectedIndex(-1);
        getContentPane().add(cb_bathroom);
        cb_bathroom.setBounds(140, 290, 177, 20);

        cb_facility.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TV 32 inch", "TV Flat 32 inch", "TV Flat 42 inch + Home Theater" }));
        cb_facility.setSelectedIndex(-1);
        getContentPane().add(cb_facility);
        cb_facility.setBounds(140, 330, 177, 20);

        btn_submit.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_submit);
        btn_submit.setBounds(140, 370, 90, 23);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int Validation(){
        int flag = 0;
        String error = "";
        
        
        if(tf_className.getText().equals("")){
            flag = 1;
            error += "Name of Class cannot be blank.\n";
        }
        if(tf_price.getText().equals("")){
            flag = 1;
            error += "Amount of Price cannot be blank.\n";
        }
        if(cb_bathroom.getSelectedIndex()==-1)
        {
            flag = 1;
            error += "Bathroom Type cannot be blank.\n";
        }
        if(cb_bedType.getSelectedIndex()==-1)
        {
            flag = 1;
            error += "Bed Type cannot be blank.\n";
        }
        if(cb_facility.getSelectedIndex()==-1)
        {
            flag = 1;
            error += "Facility cannot be blank.\n";
        }
        if(cb_roomSize.getSelectedIndex()==-1)
        {
            flag = 1;
            error += "Room Size cannot be blank.\n";
        }
        
        
        if(flag == 0)
        {
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, error);
        }
        return flag;
    }
    
    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        if(Validation() == 0){
            String idclass = tf_idClass.getText();
            String classname = tf_className.getText();
            String price = tf_price.getText();
            String bedtype = cb_bedType.getSelectedItem().toString();
            String roomsize = cb_roomSize.getSelectedItem().toString();
            String bathroom = cb_bathroom.getSelectedItem().toString();
            String facility = cb_facility.getSelectedItem().toString();

            try
            {
                    Koneksi kon = new Koneksi();
                    Connection con = kon.open();
                    String sql = "insert tb_class values(?,?,?,?,?,?,?)";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, idclass);
                    ps.setString(2, classname);
                    ps.setString(3, price);
                    ps.setString(4, bedtype);
                    ps.setString(5, roomsize);
                    ps.setString(6, bathroom);
                    ps.setString(7, facility);
                    int rows =ps.executeUpdate();
                    if(rows!=0)
                    {
                        JOptionPane.showMessageDialog(this, "Data Successfully Added");

                        ClearForm();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Terjadi Kesalahan");
                    }


            }
            catch(Exception e)
            {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void tf_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_priceKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') || (c == evt.VK_BACK_SPACE) || (c == evt.VK_DELETE))) 
        {
            evt.consume();
        }
    }//GEN-LAST:event_tf_priceKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        this.hide();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void ClearForm(){
       tf_idClass.setText(null);
       tf_className.setText(null);
       tf_price.setText(null);
       cb_bedType.setSelectedIndex(-1);
       cb_roomSize.setSelectedIndex(-1);
       cb_bathroom.setSelectedIndex(-1);
       cb_facility.setSelectedIndex(-1);
        AutoGenerateID auto = new AutoGenerateID();
        tf_idClass.setText(auto.autoIDClass());
       
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox cb_bathroom;
    private javax.swing.JComboBox cb_bedType;
    private javax.swing.JComboBox cb_facility;
    private javax.swing.JComboBox cb_roomSize;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tf_className;
    private javax.swing.JTextField tf_idClass;
    private javax.swing.JTextField tf_price;
    // End of variables declaration//GEN-END:variables
}
