
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KIDDY
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btn_class = new javax.swing.JButton();
        btn_room = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(251, 227, 96));
        jLabel4.setText("Room");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(790, 600, 110, 50);

        btn_class.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_class.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Class.jpg"))); // NOI18N
        btn_class.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 227, 96), 2, true));
        btn_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_classActionPerformed(evt);
            }
        });
        getContentPane().add(btn_class);
        btn_class.setBounds(410, 380, 200, 200);

        btn_room.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_room.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/room.jpg"))); // NOI18N
        btn_room.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 227, 96), 2, true));
        btn_room.setMaximumSize(new java.awt.Dimension(200, 200));
        btn_room.setMinimumSize(new java.awt.Dimension(200, 200));
        btn_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_roomActionPerformed(evt);
            }
        });
        getContentPane().add(btn_room);
        btn_room.setBounds(740, 380, 200, 200);

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(251, 227, 96));
        jLabel5.setText("Class");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(450, 600, 110, 50);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 610, 34, 14);

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 30, 120, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adminpnl.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1366, 768);

        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 150, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_classActionPerformed
        // TODO add your handling code here:
        Class cs = new Class();
        cs.setLocationRelativeTo(null);
        cs.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btn_classActionPerformed

    private void btn_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_roomActionPerformed
        // TODO add your handling code here:
        Room rm = new Room();
        rm.setLocationRelativeTo(null);
        rm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btn_roomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Are you sure?", "Logout", JOptionPane.YES_NO_OPTION);
        if(result==JOptionPane.YES_OPTION){
        
        Login rm = new Login();
        rm.setLocationRelativeTo(null);
        rm.setVisible(true);
        this.hide();
        }
                   
                       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_class;
    private javax.swing.JButton btn_room;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
