/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KIDDY
 */
public class Class extends javax.swing.JFrame {

    static void forName(String commicrosoftsqlserverjdbcSQLServerDriver) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form Class
     */
    public Class() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_addClass = new javax.swing.JButton();
        btn_updateClass = new javax.swing.JButton();
        btn_displayClass = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(251, 227, 96));
        jLabel3.setText("Class Panel");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(517, 87, 320, 60);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Class Panel");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 90, 320, 60);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(251, 227, 96));
        jLabel4.setText("Display Class");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(810, 540, 240, 60);

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(251, 227, 96));
        jLabel5.setText("Add Class");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 540, 180, 60);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(251, 227, 96));
        jLabel6.setText("Update Class");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(540, 540, 240, 60);

        btn_addClass.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_addClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addclass.jpg"))); // NOI18N
        btn_addClass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 227, 96), 2, true));
        btn_addClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addClassActionPerformed(evt);
            }
        });
        getContentPane().add(btn_addClass);
        btn_addClass.setBounds(290, 330, 200, 200);

        btn_updateClass.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_updateClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editclass.jpg"))); // NOI18N
        btn_updateClass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 227, 96), 2, true));
        btn_updateClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateClassActionPerformed(evt);
            }
        });
        getContentPane().add(btn_updateClass);
        btn_updateClass.setBounds(560, 330, 200, 200);

        btn_displayClass.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_displayClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/displayclass.jpg"))); // NOI18N
        btn_displayClass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 227, 96), 2, true));
        btn_displayClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_displayClassActionPerformed(evt);
            }
        });
        getContentPane().add(btn_displayClass);
        btn_displayClass.setBounds(830, 330, 200, 200);

        jButton1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jButton1.setText("Back to Mainmenu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 660, 320, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_displayClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_displayClassActionPerformed
        // TODO add your handling code here:
        DisplayClass dc = new DisplayClass();
        dc.setLocationRelativeTo(null);
        dc.setVisible(true);
        //this.hide();
    }//GEN-LAST:event_btn_displayClassActionPerformed

    private void btn_updateClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateClassActionPerformed
        // TODO add your handling code here:
        UpdateClass uc = new UpdateClass();
        uc.setLocationRelativeTo(null);
        uc.setVisible(true);
        //this.hide();
    }//GEN-LAST:event_btn_updateClassActionPerformed

    private void btn_addClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addClassActionPerformed
        // TODO add your handling code here:
        AddClass ac = new AddClass();
        ac.setLocationRelativeTo(null);
        ac.setVisible(true);
        //this.hide();
    }//GEN-LAST:event_btn_addClassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Admin adm = new Admin();
        adm.setLocationRelativeTo(null);
        adm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Class().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addClass;
    private javax.swing.JButton btn_displayClass;
    private javax.swing.JButton btn_updateClass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
