/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KIDDY
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_addCustomer = new javax.swing.JButton();
        btn_updateCustomer = new javax.swing.JButton();
        btn_displayCustomer = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        btn_addCustomer.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_addCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addcust.jpg"))); // NOI18N
        btn_addCustomer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 227, 96), 2, true));
        btn_addCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_addCustomer);
        btn_addCustomer.setBounds(280, 300, 200, 200);

        btn_updateCustomer.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_updateCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editcust.jpg"))); // NOI18N
        btn_updateCustomer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 227, 96), 2, true));
        btn_updateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_updateCustomer);
        btn_updateCustomer.setBounds(580, 300, 200, 200);

        btn_displayCustomer.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_displayCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/displaycust.jpg"))); // NOI18N
        btn_displayCustomer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 227, 96), 2, true));
        btn_displayCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_displayCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_displayCustomer);
        btn_displayCustomer.setBounds(870, 300, 200, 200);

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(251, 227, 96));
        jLabel12.setText("Add");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(340, 500, 90, 60);

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(251, 227, 96));
        jLabel11.setText("Customer");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(290, 550, 180, 60);

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(251, 227, 96));
        jLabel10.setText("Customer");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(600, 550, 180, 60);

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(251, 227, 96));
        jLabel9.setText("Update");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(610, 500, 140, 60);

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(251, 227, 96));
        jLabel8.setText("Customer");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(890, 550, 180, 60);

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(251, 227, 96));
        jLabel7.setText("Display");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(900, 500, 140, 60);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(251, 227, 96));
        jLabel3.setText("Customer Panel");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(485, 95, 400, 60);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Customer Panel");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(490, 100, 400, 60);

        jButton1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jButton1.setText("Back to Mainmenu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 660, 320, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addCustomerActionPerformed
        // TODO add your handling code here:
        AddCustomer acr = new AddCustomer();
        acr.setLocationRelativeTo(null);
        acr.setVisible(true);
        
    }//GEN-LAST:event_btn_addCustomerActionPerformed

    private void btn_updateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateCustomerActionPerformed
        // TODO add your handling code here:
        UpdateCustomer ucr = new UpdateCustomer();
        ucr.setLocationRelativeTo(null);
        ucr.setVisible(true);
        
    }//GEN-LAST:event_btn_updateCustomerActionPerformed

    private void btn_displayCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_displayCustomerActionPerformed
        // TODO add your handling code here:
        DisplayCustomer dcr = new DisplayCustomer();
        dcr.setLocationRelativeTo(null);
        dcr.setVisible(true);
        
    }//GEN-LAST:event_btn_displayCustomerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Receptionist adm = new Receptionist();
        adm.setLocationRelativeTo(null);
        adm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addCustomer;
    private javax.swing.JButton btn_displayCustomer;
    private javax.swing.JButton btn_updateCustomer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
