/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KIDDY
 * 
 *
 */
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class DisplayRoom extends javax.swing.JFrame {

    /**
     * Creates new form DisplayRoom
     */
    public DisplayRoom() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
        loadTable();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_searchIDRoom = new javax.swing.JTextField();
        btn_searchIDRoom = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_room = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 400));
        setMinimumSize(new java.awt.Dimension(450, 400));
        setPreferredSize(new java.awt.Dimension(450, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(450, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Display Room");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 40, 277, 55);

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Room");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 119, 52, 15);
        getContentPane().add(tf_searchIDRoom);
        tf_searchIDRoom.setBounds(120, 116, 101, 20);

        btn_searchIDRoom.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_searchIDRoom.setText("Search");
        btn_searchIDRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchIDRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btn_searchIDRoom);
        btn_searchIDRoom.setBounds(227, 115, 73, 23);

        tb_room.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_room);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 156, 311, 218);

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 10, 70, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadTable()
    {
        try
        {
            Koneksi kon = new Koneksi();
            Connection con = kon.open();
            
            String sql = "select * from tb_room2";
            Statement state = con.createStatement();
            ResultSet rs = state.executeQuery(sql);
            
            tb_room.setModel(DbUtils.resultSetToTableModel(rs));
            con.close();
        }
        catch(Exception e)
        {
            System.err.println(e);
        }
    }
    
    public void loadTable2(String idbarang)
    {
        try
        {
            Koneksi kon = new Koneksi();
            Connection con = kon.open();
            
            String sql = "select * from tb_room2 where id_room = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, idbarang);
            ResultSet rs = ps.executeQuery();
            
            tb_room.setModel(DbUtils.resultSetToTableModel(rs));
            con.close();
        }
        catch(Exception e)
        {
            System.err.println(e);
        }
    }
    
    private void btn_searchIDRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchIDRoomActionPerformed
        // TODO add your handling code here:
          try{
                Koneksi kon = new Koneksi();
                Connection con = kon.open();
                String sql = "select * from tb_room2 where id_room = ?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, tf_searchIDRoom.getText());
                ResultSet rs = ps.executeQuery();

                if(rs.next())
                {
                    loadTable2(tf_searchIDRoom.getText());

                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Data Not Found.");
                    
                }
            }
            catch(Exception e){
                System.err.println(e);
            }
        
    }//GEN-LAST:event_btn_searchIDRoomActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayRoom().setVisible(true);
            }
        });
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_searchIDRoom;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_room;
    private javax.swing.JTextField tf_searchIDRoom;
    // End of variables declaration//GEN-END:variables
}
