/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KIDDY
 */

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class DisplayClass extends javax.swing.JFrame {

    /**
     * Creates new form DisplayClass
     */
    public DisplayClass() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_class = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tf_searchIDClass = new javax.swing.JTextField();
        tf_search = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 400));
        setMinimumSize(new java.awt.Dimension(450, 400));
        setPreferredSize(new java.awt.Dimension(450, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(450, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Display Class");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 30, 270, 55);

        tb_class.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_class);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 160, 375, 226);

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Class");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 120, 46, 15);
        getContentPane().add(tf_searchIDClass);
        tf_searchIDClass.setBounds(80, 120, 95, 20);

        tf_search.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        tf_search.setText("Search");
        tf_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_searchActionPerformed(evt);
            }
        });
        getContentPane().add(tf_search);
        tf_search.setBounds(180, 120, 90, 23);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 70, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_searchActionPerformed
        // TODO add your handling code here:
            try{
                Koneksi kon = new Koneksi();
                Connection con = kon.open();
                String sql = "select * from tb_class where id_class = ?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, tf_searchIDClass.getText());
                ResultSet rs = ps.executeQuery();

                if(rs.next())
                {
                    loadTable2(tf_searchIDClass.getText());

                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Data Not Found.");
                    tf_searchIDClass.setText(null);
                }
            }
            catch(Exception e){
                System.err.println(e);
            }
    }//GEN-LAST:event_tf_searchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        
        this.hide();

    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void loadTable2(String idbarang)
    {
        try
        {
            Koneksi kon = new Koneksi();
            Connection con = kon.open();
            
            String sql = "select * from tb_class where id_class = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, idbarang);
            ResultSet rs = ps.executeQuery();
            
            tb_class.setModel(DbUtils.resultSetToTableModel(rs));
            con.close();
        }
        catch(Exception e)
        {
            System.err.println(e);
        }
    }
    
     public void loadTable()
    {
        try
        {
            Koneksi kon = new Koneksi();
            Connection con = kon.open();
            
            String sql = "select * from tb_class";
            Statement state = con.createStatement();
            ResultSet rs = state.executeQuery(sql);
            
            tb_class.setModel(DbUtils.resultSetToTableModel(rs));
            con.close();
        }
        catch(Exception e)
        {
            System.err.println(e);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_class;
    private javax.swing.JButton tf_search;
    private javax.swing.JTextField tf_searchIDClass;
    // End of variables declaration//GEN-END:variables
}
